name: CI
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: "Lint package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --frozen-lockfile
      - run: npm run lint